#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [ ]:


def slope(coeffs, x):

    return 3 * a * x * x + 2 * b * x + c

a = float(input("Enter cubic term: "))
b = float(input("Enter quadratic term: "))
c = float(input("Enter linear term: "))
d = float(input("Enter constant term: "))
x = float(input("Enter value of x: "))

coeffs=(a, b, c, d)



print("The slope is", slope(coeffs, x))

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
import numpy as np
arr=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(arr)

In [1]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
import numpy as np
arr=np.arange(0, 20, 4)
print(arr)
# Hint : Use np.arange or np.linspace

[ 0  4  8 12 16]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
newarr1=np.add(a,b)
newarr2=np.subtract(a,b)
newarr3=np.multiply(a,b)
newarr4=np.divide(a,b)
print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)


In [2]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
newarr1=np.sum([a, b], axis=0)
print(newarr1)
# Write a NumPy function to get the sum of the array 'a' along axis=1
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
newarr2=np.sum([a, b], axis=1)
print(newarr2)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]


In [1]:
# Write a NumPy function to reverse the array 'a'
import numpy as np

a = np.array([[-4, 6, 8],
              [ 9, 3, 1],
              [ 1, 8, 5]])

rev = a[::-1, ::-1]
print(rev)
# Write a NumPy function to reverse the array 'a' along axis=0
rev_axis0 = a[::-1, :]
print(rev_axis0)
# Write a NumPy function to reverse the array 'a' along axis=1
rev_axis1 = a[:, ::-1]
print(rev_axis1)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [2]:
# Write a NumPy function to sort the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
newarr=np.sort(a)
print(newarr)
# Write a NumPy function to sort the array 'a' along axis=0
newarr1=np.sort(a, axis=0)
print(newarr1)
# Write a NumPy function to sort the array 'a' along axis=1
newarr2=np.sort(a, axis=1)
print(newarr2)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
newarr3=newarr1[::-1]
print(newarr3)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
argsorta_axis_0=np.argsort(a, axis=0)
print(a)
# Write a NumPy function to argsort the array along axis=1
argsorta_axis_1=np.argsort(a, axis=1)
print(argsorta_axis_1)

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
arr=np.concatenate((a,b), axis=0)
print(arr)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
print(a.ndim)
print(a.shape)
print(a.size)
# Write a NumPy function to get the Shape of the array

# Write a NumPy function to get the Size of the array

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
import numpy as np
a=np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
newarr=a.reshape(1,9)
print(newarr)

In [3]:
# Write a NumPy function to add a new axis to the array 'a'
import numpy as np
a=np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
newarr=np.expand_dims(a, axis=1)
print(newarr)
# Note : Show atleast two different ways of doing this
newarr1 = a[np.newaxis, :]
print(newarr1)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
print(a[3,2])
print(a[3])
print(a[0:2, 0:2])
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
newarr=a[a>4]
print(newarr)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
newarr1=a[(a>4) & (a%2==0)]
print(newarr1)

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [3]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
x=a.copy()
print(x+1)


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [9]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd

df1 = pd.DataFrame(iris_2d)
clean_df1 = df1.dropna()
clean_df1

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean_val = df1[2].mean()
median_val = df1[2].median()
std_val = df1[2].std()

mean_val,
median_val,
std_val

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
df1[[0,1]].corr()

In [11]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import numpy as np
volume = (np.pi * df1[2] * (df1[0]**2)) / 3
df1['volume'] = volume

NameError: name 'df1' is not defined

### Miscellaneous

Q1 - Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

Q2- Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

### PANDAS

Run the following cell before proceeding further


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

      Q3-Write a Pandas function to find the count of unique species. 

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
df = pd.DataFrame(iris, columns=names)
bins = [0, 3, 5, 100]
labels = ['small', 'medium', 'large']

df['petalsize'] = pd.cut(df['petallength'].astype(float), bins=bins, labels=labels, right=False)

print(df[['petallength', 'petalsize']])

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
mostfreq = df['petallength'].mode()
print(mostfreq)