<a href="https://colab.research.google.com/github/namanbansal2710/DataDiction/blob/main/250695_NamanBansal_assgn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [ ]:
a=eval(input("enter tuple"))
b=int(input("enter the value"))
def slope_of_cubic(c,d):
  e=3*(c[0])*d*d+2*(c[1])*d+c[2]
  return e
print(slope_of_cubic(a,b))


enter tuple(1,2,3,4)
enter the value1
10


##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
import numpy as np
list1 = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
array1 = np.array(list1)
print(array1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
import numpy as np
def randomarray():
  arr = np.empty([3,4])
def array0():
  arr=np.zeros([3,4])



In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
import numpy as np
def array_function():
  arr=np.arange(0,10,2)
  print(arr)
array_function()

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def add_array():
  c=np.add(a,b)
  return c
add_array()
def subtract_array():
  c=np.subtract(a,b)
  return c
subtract_array()
def multiply_array():
  c=np.multiply(a,b)
  return c
multiply_array()
def divide_array():
  c=np.divide(a,b)
  return c
divide_array()


array([[-0.36363636,  0.375     ,  0.44444444],
       [ 0.1       ,  0.08108108,  0.01234568],
       [ 0.01639344,  0.16666667,  0.06666667]])

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1
def axis0():
  print(np.sum(a, axis = 0))
def axis1():
  print(np.sum(a, axis = 1))
axis0()
axis1()

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
def reverse():
  np.flip(a)


# Write a NumPy function to reverse the array 'a' along axis=0
def reverse0():
  np.flipud(a)


# Write a NumPy function to reverse the array 'a' along axis=1
def reverse1():
  np.fliplr(a)


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
import numpy as np
def sort1():
  return np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
def sort2():
  return np.sort(a,axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
def sort3():
  return np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort4():
  return np.flipud(np.sort(a,axis=0))

print(sort1())
print(sort2())
print(sort3())
print(sort4())

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
def sort5(arr):
  return np.argsort(arr,axis=0)


# Write a NumPy function to argsort the array along axis=1
def sort6(arr):
  return np.argsort(arr,axis=1)


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def conc1():
  return np.concatenate((a,b),axis=None)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def conc2():
  return np.concatenate((a,b),axis=0)


# Note: You can do the same function using stacking, discover and try that :)
def conc3():
  return np.stack((a,b))



[-4  6  8  9  3  1  1  8  5 11 16 18 90 37 81 61 48 75]
[[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def dimension():
  return a.ndim

# Write a NumPy function to get the Shape of the array
def shape():
  return a.shape
# Write a NumPy function to get the Size of the array
def size():
  return np.size(a)


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape():
  return a.reshape(1,9)


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
def new_axis1():
  np.expand_dims(a,axis=0)


def new_axis2():
  return a.reshape(1,3,3)
# Note : Show atleast two different ways of doing this

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
def index1(a):
  print(a[0])
def index2(a):
  print(a[1,2])
def index3(a):
  print(a[0:2,1:3])

# Show all three - indexing by a integer, indexing by a tuple, using range

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def greater_than_four(a):
    return a[a > 4]


# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def greater_than_four_divisible_by_2(a):
    return a[(a > 4) & (a%2==0)]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy(a):
    a_copy = a.copy()
    a_copy = a_copy + 1
    return a_copy

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
import numpy as np

def drop_missing_rows():
    df = pd.DataFrame(iris_2d)
    df_clean = df.dropna()
    return df_clean
print(drop_missing_rows())

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def mean_column_3():
    df = pd.DataFrame(iris_2d)
    column = df[3]   # select column 3 (0-indexed)

    return {
        'mean': column.mean(),
        'median': column.median(),
        'std': column.std()
    }


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
def correlation():
    df = pd.DataFrame(iris_2d)
    return df[0].corr(df[1])

-0.10936924995064937


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
def new_column():
    df = pd.DataFrame(iris_2d, columns=['sepal_length','sepal_width','petal_length','petal_width'])
    volume = (np.pi * df['petal_length'] * (df['sepal_length'] ** 2)) / 3
    volume_2d = volume.values.reshape(-1, 1)
    df['volume'] = volume_2d

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.uniform(0, 10, (2, 5))
print(x)
print(np.max(x, axis=1))
print(np.min(x, axis=1))

[[1.70870462 3.47324469 8.87931737 8.972375   0.65468025]
 [5.12384684 2.04580314 8.93684692 7.43558762 0.01795059]]
[8.972375   8.93684692]
[0.65468025 0.01795059]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1, 10)
a, b, c = np.split(x, [4, 6])

print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


### PANDAS

Run the following cell before proceeding further


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

In [ ]:
def unique_species():
    df = pd.DataFrame(iris, columns=names)
    return df['species'].nunique()


# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
def bin_petal_length(arr):
    df = pd.DataFrame(arr, columns=['sepallength','sepalwidth','petallength','petalwidth'])
    bins = [0, 3, 5, np.inf]
    labels = ['small', 'medium', 'large']
    df['petal_length_bin'] = pd.cut(df['petallength'].astype(float), bins=bins, labels=labels, right=False)
    return df['petal_length_bin']
binned = bin_petal_length(iris_2d)
print(binned.head())

0    small
1    small
2    small
3    small
4    small
Name: petal_length_bin, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
def most_frequent_value():
    df = pd.DataFrame(iris, columns=names)
    petal_length = df['petallength'].astype(float)
    return petal_length.mode()[0]

Most frequent petal length: 1.5
