#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [ ]:
def slope_of_cubic(a, b, c, d, x):
    slope = 3 * a * x * x + 2 * b * x + c
    return slope

a = float(input("Enter coefficient of x^3 (a): "))
b = float(input("Enter coefficient of x^2 (b): "))
c = float(input("Enter coefficient of x (c): "))
d = float(input("Enter constant (d): "))
x = float(input("Enter value of x: "))

ans = slope_of_cubic(a, b, c, d, x)
print("Slope at x is:", ans)



##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
import numpy as np

mylist = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = np.array(mylist)
print(arr)


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy as np

arr = np.random.randint(1, 10, (3, 4))
print(arr)


# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
import numpy as np

arr = np.zeros((3, 4))
print(arr)


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
import numpy as np

a = np.array([[-4, 6, 8],
              [ 9, 3, 1],
              [ 1, 8, 5]])

b = np.array([[11, 16, 18],
              [90, 37, 81],
              [61, 48, 75]])

# Addition
add = a + b
print("Addition:\n", add)

# Subtraction
sub = a - b
print("\nSubtraction:\n", sub)

# Multiplication
mul = a * b
print("\nMultiplication:\n", mul)

# Division
div = a / b
print("\nDivision:\n", div)


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
import numpy as np

sum_axis_0 = np.sum(a, axis=0)
print(sum_axis_0)


# Write a NumPy function to get the sum of the array 'a' along axis=1
import numpy as np

sum_axis_1 = np.sum(a, axis=1)
print(sum_axis_1)


[ 5 17  6]


In [ ]:
# Write a NumPy function to reverse the array 'a'

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
import numpy as np


a = np.array([[-4, 6, 8], [9, 3, 1], [1, 8, 5]])


sorted_a = np.sort(a, axis=None)

print("Original array:\n", a)
print("Sorted array:\n", sorted_a)


# Write a NumPy function to sort the array 'a' along axis=0
import numpy as np

# Original array
a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


sorted_a = np.sort(a, axis=0)

print("Original array:\n", a)
print("Array sorted along columns:\n", sorted_a)


# Write a NumPy function to sort the array 'a' along axis=1
import numpy as np

a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


sorted_a = np.sort(a, axis=1)

print("Original array:\n", a)
print("Array sorted along rows:\n", sorted_a)


# Write a NumPy function to sort the array 'a' in descending order along axis=0
import numpy as np

a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


sorted_a_desc = np.flip(np.sort(a, axis=0), axis=0)

print("Original array:\n", a)
print("Array sorted along columns (descending):\n", sorted_a_desc)


Original array:
 [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
Sorted array:
 [-4  1  1  3  5  6  8  8  9]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np

def argsortaxis0(arr):

    return np.argsort(arr, axis=0)


a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

sortedindices = argsortaxis0(a)

print("Original array:\n", a)
print("Indices for column-wise sorting:\n", sortedindices)

# Write a NumPy function to argsort the array along axis=1
import numpy as np

def argsort_rows(arr):

    return np.argsort(arr, axis=1)


a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

row_indices = argsort_rows(a)

print("Original array:\n", a)
print("Row-wise argsort indices:\n", row_indices)



In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np


a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

b = np.array([[11, 16, 18],
              [90, 37, 81],
              [61, 48, 75]])

concat_rows = np.concatenate((a, b), axis=0)
print("Concatenate along rows:\n", concat_rows)

concat_cols = np.concatenate((a, b), axis=1)
print("Concatenate along columns:\n", concat_cols)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
import numpy as np

def concatenate_axis0(a, b):

    return np.concatenate((a, b), axis=0)


a = np.array([[-4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

b = np.array([[11, 16, 18],
              [90, 37, 81],
              [61, 48, 75]])

result = concatenate_axis0(a, b)
print

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np

a = np.array([[4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


num_dims = a.ndim

print("Array:\n", a)
print("Number of dimensions:", num_dims)


# Write a NumPy function to get the Shape of the array
import numpy as np

a = np.array([[4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

shape = a.shape

print("Array:\n", a)
print("Shape of the array:", shape)


# Write a NumPy function to get the Size of the array
import numpy as np


a = np.array([[4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


size = a.size

print("Array:\n", a)
print("Total number of elements:", size)


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
import numpy as np

a = np.array([[4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])


reshaped_a = a.reshape(1, 9)

print("Original array:\n", a)
print("Reshaped array (1, 9):\n", reshaped_a)


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
import numpy as np

# Original array
a = np.array([[4, 6, 8],
              [9, 3, 1],
              [1, 8, 5]])

# Method 1: Using np.newaxis
new_axis1 = a[:, :, np.newaxis]  # Adds a new third dimension

# Method 2: Using np.expand_dims
new_axis2 = np.expand_dims(a, axis=2)  # axis=2 means new third dimension

print("Original array shape:", a.shape)
print("Method 1 shape:", new_axis1.shape)
print("Method 2 shape:", new_axis2.shape)


# Note : Show atleast two different ways of doing this

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
import numpy as np


a = np.array([[4, 6, 0],
              [0, 3, 1],
              [1, 8, 5]])


print("Element at row 0, column 1:", a[0, 1])


print("Row 1:", a[1, :])


print("Column 2:", a[:, 2])


print("Sub-array:\n", a[0:2, 1:3])


print("Last element:", a[-1, -1])

# Show all three - indexing by a integer, indexing by a tuple, using range
import numpy as np

a = np.array([[4, 6, 0],
              [0, 3, 1],
              [1, 8, 5]])


print("Row 1 (integer indexing):", a[1])


print("Element at row 0, column 1 (tuple indexing):", a[(0, 1)])


print("Sub-array using range/slice:\n", a[0:2, 1:3])


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
import numpy as np


a = np.array([[4, 6, 0],
              [0, 3, 1],
              [1, 8, 5]])

greater_than_4 = a[a > 4]

print("Original array:\n", a)
print("Values greater than 4:", greater_than_4)


# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
import numpy as np

a = np.array([[4, 6, 0],
              [0, 3, 1],
              [1, 8, 5]])


selected_values = a[(a > 4) & (a % 2 == 0)]

print("Original array:\n", a)
print("Values greater than 4 and divisible by 2:", selected_values)


Original array:
 [[4 6 0]
 [0 3 1]
 [1 8 5]]
Values greater than 4: [6 8 5]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])


b = np.copy(a)


b = b + 1

print(b)



## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import numpy as np
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genf
df = pd.DataFrame(iris_2d)

df_clean = df.dropna()

print(df_clean)


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.

mean_val = df_clean.iloc[:, 3].mean()
median_val = df_clean.iloc[:, 3].median()
std_val = df_clean.iloc[:, 3].std()

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.

correlation = df_clean.iloc[:, 0].corr(df_clean.iloc[:, 1])

print("Correlation between Column 0 and Column 1:", correlation)


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import numpy as np


volume = (np.pi * df_clean.iloc[:, 2] * (df_clean.iloc[:, 0] ** 2)) / 3

df_clean['volume'] = volume

print(df_clean.head())


### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np


x = np.random.uniform(0, 10, (2, 5))

print("Array x:\n", x)


max_vals = np.max(x, axis=1)
max_indices = np.argmax(x, axis=1)

min_vals = np.min(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("\nMaximum values:", max_vals)
print("Indices of maximum values:", max_indices)

print("\nMinimum values:", min_vals)
print("Indices of minimum values:", min_in_


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np


x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


a, b, c = np.split(x, [4, 6])

print("First array:", a)
print("Second array:", b)
print("Third array:", c)


### PANDAS

Run the following cell before proceeding further


In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

import pandas as pd


df_iris = pd.DataFrame(iris, columns=names)


df_iris.iloc[:, 0:4] = df_iris.iloc[:, 0:4].astype(float)

print(df_iris.head())


Q3- Write a Pandas function to find the count of unique species.

In [ ]:
#
unique_species_count = df_iris['species'].nunique()

print("Number of unique species:", unique_species_count)


# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
import numpy as np


df = pd.DataFrame(iris_2d, columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])

bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']

df['petal_size'] = pd.cut(df['petallength'], bins=bins, labels=labels)

print(df[['petallength', 'petal_size']].head())


Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:

most_frequent = df_iris['petallength'].mode()[0]

print("Most frequent value of petal length:", most_frequent)
