#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [900]:
def slope_of_cubic(coefficients, x):
  y= coefficients[0]*3*x**2 +  coefficients[1]*2*x +  coefficients[2]
  return y

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [901]:
import numpy as np

In [902]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [903]:
# Write a NumPy function to create an array with random values of shape [3,4]
def random_array():
    return np.random.rand(3,4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def create_zero_array():
    return np.zeros((3,4))

In [904]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
np.arange(10,25,5)

array([10, 15, 20])

### Basic array operations
- algebraic operations
- logical operations

In [905]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [906]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def array_operations(a,b):
 add_result=a+b
 subt_result=a-b
 mul_result=a*B
 div_result=a/b
 return {
        "addition": add_result,
        "subtraction": sub_result,
        "multiplication": mul_result,
        "division": div_result
    }




In [907]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum_along_axis_0(a):
    return np.sum(a, axis=0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum_along_axis_1(a):
    return np.sum(a, axis=1)

In [908]:
# Write a NumPy function to reverse the array 'a'
def reverse_array(a):
    return a[::-1]

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_array_axis_0(a):
    return np.flip(a, axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_axis_1(a):
    return np.flip(a, axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [909]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [910]:
# Write a NumPy function to sort the array 'a'
def sort_array(a):
    return np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
def sort_array_axis_0(a):
    return np.sort(a, axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
def sort_array_axis_1(a):
    return np.sort(a, axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_array_axis_0_desc(a):
    return np.sort(a, axis=0)[::-1]


In [911]:
# Write a NumPy function to argsort the array along axis=0
def argsort_array_axis_0(a):
    return np.argsort(a, axis=0)
# Write a NumPy function to argsort the array along axis=1
def argsort_array_axis_1(a):
    return np.argsort(a, axis=1)


In [912]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concat_array(a, b):
    return np.concatenate((a, b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concat_array_axis_0(a, b):
    return np.concatenate((a, b), axis=0)

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [913]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [914]:
# Write a NumPy function to get the Number of dimensions
def get_num_dimensions(a):
    return a.ndim

# Write a NumPy function to get the Shape of the array
def get_shape(a):
    return a.shape

# Write a NumPy function to get the Size of the array
def get_size(a):
    return a.size

In [915]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_array(a):
    return a.reshape(1,9)

In [916]:
# Write a NumPy function to add a new axis to the array 'a'
def add_newaxis(a):
    return np.expand_dims(a, axis=0)
def add_newaxis_axis_1(a):
    return np.expand_dims(a, axis=1)

# Note : Show atleast two different ways of doing this

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [917]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [918]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def index_array(a):
    return a[1,2]
    return a[1]
    return a[1:3,0:2]



In [919]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def select_values(a):
    return a[a>4]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def select_values_multiple_conditions(a):
    return a[(a>4) & (a%2==0)]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [920]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [921]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy_array(a):
    b=a.copy()
    b=b+1
    print(b)
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
copy_array(a)


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [922]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [923]:
# Write a Pandas function to drop rows that contain a missing value.
def drop_missing_values(iris_2d):
  df=pd.DataFrame(iris_2d)
  df.dropna(inplace=True)
  return df

In [924]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def get_stats(iris_2d):
  df=pd.DataFrame(iris_2d)
  col=df.iloc[:,2]
  mean=col.mean()
  median=col.median()
  std=col.std()
  return {
      "mean": mean,
      "median": median,
      "std": std
  }


In [925]:
# Write a Pandas function to find the correlation between the first two columns.
def get_correlation(iris_2d):
  df=pd.DataFrame(iris_2d)
  col1=df.iloc[:,0]
  col2=df.iloc[:,1]
  corr=col1.corr(col2)
  return corr


In [926]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
def add_volume_column(iris_2d):
  df=pd.DataFrame(iris_2d)
  volume=(np.pi*df.iloc[:,2]*df.iloc[:,0]**2)/3
  df["volume"]=volume
  return df

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [927]:
x=np.random.randint(0,10,size=(2,5))
max_value=np.max(x)
min_value=np.min(x)
max_index=np.argmax(x,axis=1)
min_index=np.argmin(x,axis=1)
print (x)
print (max_value)
print (min_value)
print (max_index)
print (min_index)

[[9 6 1 3 8]
 [2 1 0 2 4]]
9
0
[0 4]
[2 2]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [928]:
def split_array(x):
  array_1=x[:4]
  array_2=x[4:6]
  array_3=x[6:]
  print (array_1)
  print (array_2)
  print (array_3)
a=[1, 2, 3, 4,5,6,7,8, 9]
split_array(a)


[1, 2, 3, 4]
[5, 6]
[7, 8, 9]


### PANDAS

Run the following cell before proceeding further


In [929]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

In [930]:
def count_unique_species(iris):
  species=iris[:,4]
  unique_species=np.unique(species)
  count=len(unique_species)
  return count
count_unique_species(iris)

3

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [931]:
def bin_petal_length(iris_2d):
  petal_length=iris_2d[:,2]
  bins=[0,3,5,np.inf]
  labels=['small','medium','large']
  binned_petal_length=np.digitize(petal_length,bins)-1
  print (np.array(labels)[binned_petal_length])

bin_petal_length(iris_2d)


['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'large' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' '

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [932]:
def most_frequent_petal_length(iris_2d):
  petal_length=iris_2d[:,2]
  unique_values,counts=np.unique(petal_length,return_counts=True)
  most_frequent_value=unique_values[np.argmax(counts)]
  return most_frequent_value
