#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [1]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy as np
rng = np.random.default_rng()
print(rng.integers(low=1, high=11, size=(3, 4)))

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
c = a + b
print(c)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.sum(a, axis=0)
print(c)

# Write a NumPy function to get the sum of the array 'a' along axis=1
c = np.sum(a, axis=1)
print(c)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.flip(a)
print(c)

# Write a NumPy function to reverse the array 'a' along axis=0
c = np.flip(a, axis=0)
print(c)

# Write a NumPy function to reverse the array 'a' along axis=1


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.sort(a)
print(c)

# Write a NumPy function to sort the array 'a' along axis=0
c = np.sort(a, axis=0)
print(c)

# Write a NumPy function to sort the array 'a' along axis=1
c = np.sort(a, axis=1)
print(c)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
c = np.sort(a, axis=0)[::-1]
print(c)


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.argsort(a, axis=0)
print(c)

# Write a NumPy function to argsort the array along axis=1
c = np.argsort(a, axis=1)
print(c)


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
c = np.concatenate((a, b), axis=0)
print(c)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
c = np.concatenate((a, b), axis=1)
print(c)

# Note: You can do the same function using stacking, discover and try that :)

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.ndim(a)
print(c)

# Write a NumPy function to get the Shape of the array
c = np.shape(a)
print(c)

# Write a NumPy function to get the Size of the array
c = np.size(a)
print(c)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
c = np.reshape(a, (1,9))
print(c)

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
b = a+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

### PANDAS

Run the following cell before proceeding further


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset